dist: trusty
sudo: required
language: cpp

compiler:
  - clang
  - gcc

before_script:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt59-trusty
  - sudo apt-get update -qq
  - sudo apt-get install qt59base qtbase5-dev libpcap-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
